# docker compose up -d --build
# docker compose down -v --remove-orphans
version: '3.9'

services:
  pipeline:
    build:
      context: ../dockerfile/
      dockerfile: dockerfile
      no_cache: true
    environment:
      TZ: America/Santiago
      TUYA_API_ENDPOINT: us # cn, us, us-e, eu, eu-w, or in. Options based on tinytuya python library
      TUYA_ACCESS_ID: this_is_an_access_id
      TUYA_ACCESS_KEY: this_is_a_super_long_secret_key
      POSTGRES_HOST: host
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: db
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: pass