FROM ubuntu:focal

# Set the Timezone
ENV TZ "America/Santiago"
# Set Tuya endpoint and api key
ENV TUYA_API_ENDPOINT = 'us'
ENV TUYA_ACCESS_ID = 'this_is_an_access_id'
ENV TUYA_ACCESS_KEY = 'this_is_a_super_long_secret_key'
# Set Postgres database configuration for connection
ENV POSTGRES_HOST "host"
ENV POSTGRES_PORT "port"
ENV POSTGRES_DATABASE "db"
ENV POSTGRES_USERNAME "user"
ENV POSTGRES_PASSWORD "pass"

# Best practices
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Set the working directory to /app and copy files there
WORKDIR /app
COPY requirements.txt scheduler.py /app/
COPY tuya_energy_consumption.ipynb /app/

RUN mkdir /app/logs
RUN touch /app/logs/logs.log

# Add timezone to the container
RUN apt update && \
    apt install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Install python3 and more
RUN apt install -y \
        python3 \
        python3-pip \
        moreutils

# Install the dependencies for python script
RUN pip install wheel setuptools pip --upgrade
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip ipython ipykernel

# Pass environments to python && Run scheduler giving every output to logs.log && Show logs.log as logs of the container
CMD printenv > /etc/environment && python3 scheduler.py 2>&1 | ts "[%Y-%m-%d %H:%M:%S]" | tee -a /app/logs/logs.log && tail -f /app/logs/logs.log
